import os
from setuptools import setup, find_packages

BUILD_ID = os.environ.get("BUILD_BUILDID", "0")

setup(
    name="dual_autodiff",
    # Author details
    author="Yuiko Ichikawa",
    author_email="",
    packages=find_packages("src"),
    package_dir={"": "src"},
    
    ## need editiong
    setup_requires=["pyspark[ml]", "sklearn", "pytest-runner"],
    tests_require=["pytest", "pytest-nunit", "pytest-cov"],
    extras_require={"develop": ["pre-commit", "bump2version"]},
)

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
write_to = "<package_folder>/version.py"  # Where to write the dynamic version

